apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../kubemacs
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=hh@ii.coop
  - GIT_NAME=Hippie Hacker
  - INIT_DEFAULT_REPO=https://github.com/cncf/apisnoop.git
  - INIT_DEFAULT_DIR=/home/ii/apisnoop/deployment/k8s/hh
  - INIT_ORG_FILE=/home/ii/apisnoop/deployment/k8s/hh/README.org:44
images:
  # We should probably move this build into prow / apisnoop
  - name: gcr.io/apisnoop/kubemacs
    newTag: 0.9.31
