apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tmate-master-ingress
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "tmate-server.kubemacs.org"
    # nginx.ingress.kubernetes.io/app-root: /pgadmin
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header X-Script-Name "/pgadmin";
    #   proxy_set_header X-Scheme $scheme;
    #   # proxy_set_header Host $host;
  # annotations:
  #   nginx.ingress.kubernetes.io/app-root: /
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "tmate-server.kubemacs.org"
    http:
      # required PGADMIN_CONFIG_SERVER_MODE env set to False in deployment
      # We need to template this out
      paths:
      # - path: /pgadmin(/|$)(.*)
      - path: /
      # required SCRIPT_NAME env in deployment
      # - path: /pgadmin
        backend:
          serviceName: master
          servicePort: 4000
