apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
data:
  POSTGRES_DB: apisnoop
  POSTGRES_USER: apisnoop
  PGDATABASE: apisnoop
  PGUSER: apisnoop
  # APISNOOP_BASELINE_BUCKET: ci-kubernetes-e2e-gci-gce
  # APISNOOP_BASELINE_JOB: 1201280603970867200
