apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.apisnoop.db: postgres
  template:
    metadata:
      labels:
        io.apisnoop.db: postgres
    spec:
      restartPolicy: Always
      containers:
      - name: postgres
        image: "raiinbow/postgres:v2020.04.09-1"
        # image: "gcr.io/k8s-staging-apisnoop/postgres:v20200211-0.9.34-1-g24cf96f"
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - "pg_isready"
            - "-U"
            - "apisnoop"
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configuration
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configuration
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-configuration
              key: POSTGRES_PASSWORD
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-configuration
              key: PGDATABASE
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: postgres-configuration
              key: PGUSER
        # - name: APISNOOP_BASELINE_BUCKET
        #   valueFrom:
        #     configMapKeyRef:
        #       name: postgres-configuration
        #       key: APISNOOP_BASELINE_BUCKET
        # - name: APISNOOP_BASELINE_JOB
        #   valueFrom:
        #     configMapKeyRef:
        #       name: postgres-configuration
        #       key: APISNOOP_BASELINE_JOB
        # - name: APISNOOP_BASELINE_BUCKET
        #   value: ci-kubernetes-e2e-gci-gce
        # - name: APISNOOP_BASELINE_JOB
        #   value: "1201280603970867200"
