apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      io.apisnoop.graphql: hasura
  template:
    metadata:
      labels:
        io.apisnoop.graphql: hasura
    spec:
      restartPolicy: Always
      containers:
      - name: hasura
        image: "raiinbow/hasura:v20200211-0.9.34-1-g24cf96f"
        ports:
        - containerPort: 8080
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: "postgres://apisnoop:apisnoop@postgres:5432/apisnoop"
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: RESTART
          value: "true"
