apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configuration
data:
  servers.json: |
    { "Servers": { "1": {
      "Name": "apisnoop",
      "Group": "Servers",
      "Host": "postgres",
      "Port": 5432,
      "MaintenanceDB": "apisnoop",
      "Username": "apisnoop",
      "SSLMode": "prefer",
      "Comment": "APISnoop Database",
      "Password": "s3cretsauc3",
      "PassFile": "/pgadmin-config/pgpass",
      "SSLCompression": 0,
      "Timeout": 10,
      "UseSSHTunnel": 0,
      "TunnelPort": "22",
      "TunnelAuthentication": 0
     }}}
  pgpass: |
    postgres:5432:apisnoop:apisnoop:s3cretsauc3
    10.96.112.46:5432:apisnoop:apisnoop:s3cretsauc3
