apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: apisnoop
# resources:
#   - basic-auth.yaml
  # - namespace.yaml
bases:
  - ../../kubemacs
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=caleb@ii.coop
  - GIT_NAME=Caleb Woodbine
  - INIT_DEFAULT_REPO=https://github.com/cncf/apisnoop.git
  - INIT_DEFAULT_DIR=/home/ii/apisnoop/deployment/k8s/xip.io
  - INIT_ORG_FILE=/home/ii/apisnoop/deployment/k8s/xip.io/README.org:44
images:
  # We should probably move this build into prow / apisnoop
  - name: gcr.io/apisnoop/kubemacs
    newTag: 0.9.28
