apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
# https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/mandatory.yaml
# https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.28.0/deploy/static/provider/baremetal/service-nodeport.yaml
# namespace: ingress-nginx
resources:
  - mandatory.yaml
  - service-nodeport.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-ingress-controller
    path: patch.yaml
