# kind-cluster-config.yaml
# #+NAME: kind kubeadm DynamicAuditing configuration

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "DynamicAuditing=true"
      "runtime-config": "auditregistration.k8s.io/v1alpha1=true"
      "audit-dynamic-configuration": "true"
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: '*.ii.nz'
    - op: add
      path: /apiServer/certSANs/-
      value: '*.ii.coop'
nodes:
 - role: control-plane
   extraMounts:
   # - containerPath: /var/local-path-provisioner
   #   hostPath: /tmp/workspace/pvcs
   #   readOnly: False
   - containerPath: /var/run/docker.sock
     hostPath: /var/run/docker.sock
     readOnly: False
   - containerPath: /var/host/tmp
     hostPath: /tmp
     readOnly: False
   extraPortMappings:
   - containerPort: 80
     hostPort: 80
   - containerPort: 443
     hostPort: 443
   - containerPort: 5432
     hostPort: 5432
   - containerPort: 6443
     hostPort: 6443
   - containerPort: 10350
     hostPort: 10350
   # - containerPort: 80
   #   hostPort: 2080
   # - containerPort: 443
   #   hostPort: 20443
   kubeadmConfigPatches:
   - |
     apiVersion: kubeadm.k8s.io/v1beta2
     kind: InitConfiguration
     nodeRegistration:
       kubeletExtraArgs:
         node-labels: "ingress-ready=true"
         authorization-mode: "AlwaysAllow"
 - role: worker
   extraMounts:
   # - containerPath: /var/local-path-provisioner
   #   hostPath: /tmp/workspace/pvcs
   #   readOnly: False
   - containerPath: /var/run/docker.sock
     hostPath: /var/run/docker.sock
     readOnly: False
   - containerPath: /var/host/tmp
     hostPath: /tmp
     readOnly: False
