apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-kubemacs
  namespace: kubemacs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-kubemacs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-kubemacs
  namespace: kubemacs
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubemacs
  labels:
    environment: production
---
apiVersion: v1
kind: Service
metadata:
  name: kubemacs-tilt
  namespace: kubemacs
spec:
  type: ClusterIP
  selector:
    app: kubemacs
  ports:
  - name: "10350"
    port: 10350
    targetPort: 10350
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemacs
  namespace: kubemacs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemacs
  template:
    metadata:
      labels:
        app: kubemacs
    spec:
      serviceAccountName: admin-kubemacs
      containers:
      - name: kubemacs
        image: gcr.io/apisnoop/kubemacs:0.9.24
        env:
          - name: TZ
            value: "Pacific/Auckland"
          - name: GIT_COMMITER_EMAIL
            value: "ii@ii.coop"
          - name: GIT_COMMITER_NAME
            value: "ii coop in New Zealand"
          - name: GIT_AUTHOR_EMAIL
            value: "ii@ii.coop"
          - name: GIT_AUTHOR_NAME
            value: "ii coop in New Zealand"
        volumeMounts:
          - mountPath: '/home/ii/workspace'
            name: kubemacs-hostpath
          - name: docker
            mountPath: /var/run/docker.sock
          - name: host-tmp
            mountPath: /tmp
      volumes:
        - name: kubemacs-hostpath
          hostPath:
            path: /workspace
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: host-tmp
          hostPath:
            path: /var/host/tmp

