apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.apisnoop.webapp: webapp
  template:
    metadata:
      labels:
        io.apisnoop.webapp: webapp
    spec:
      restartPolicy: Always
      containers:
      - name: webapp
        image: "raiinbow/webapp:v2020.04.08-1"
        # image: "gcr.io/k8s-staging-apisnoop/webapp:v20200211-0.9.34-1-g24cf96f"
        ports:
        - containerPort: 3000
