apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubemacs
spec:
  replicas: 1
  serviceName: "kubemacs"
  selector:
    matchLabels:
      app: kubemacs
  template:
    metadata:
      labels:
        app: kubemacs
    spec:
      serviceAccountName: kubemacs-sa
      containers:
      - name: kubemacs
        image: gcr.io/apisnoop/kubemacs:0.9.30
        command:
          - /usr/local/bin/simple-init.sh
          - "$INIT_ORG_FILE"
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: TZ
          - name: GIT_COMMITTER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: GIT_EMAIL
          - name: GIT_COMMITTER_NAME
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: GIT_NAME
          - name: GIT_AUTHOR_EMAIL
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: GIT_EMAIL
          - name: GIT_AUTHOR_NAME
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: GIT_NAME
          - name: INIT_DEFAULT_REPO
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: INIT_DEFAULT_REPO
          - name: INIT_DEFAULT_DIR
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: INIT_DEFAULT_DIR
          - name: INIT_ORG_FILE
            valueFrom:
              configMapKeyRef:
                name: kubemacs-configuration
                key: INIT_ORG_FILE
        volumeMounts:
          - mountPath: '/home/ii/workspace'
            name: kubemacs-hostpath
          - name: docker
            mountPath: /var/run/docker.sock
          - name: host-tmp
            mountPath: /tmp
      volumes:
        - name: kubemacs-hostpath
          hostPath:
            path: /workspace
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: host-tmp
          hostPath:
            path: /var/host/tmp

